sudo: false
language: ruby
cache: bundler
branches:
  only:
    - master
rvm:
  - 2.1
script:
  - bundle exec jekyll build
  - bundle exec htmlproof ./_site --only-4xx --check-favicon --check-html --empty-alt-ignore --ignore-script-embeds
  - bundle exec httparty -f json "http://geojsonlint.com/validate?url=https://raw.githubusercontent.com/maptime/maptime.github.io/master/_data/chapters.json"
env:
  global:
    - NOKOGIRI_USE_SYSTEM_LIBRARIES=true # speeds up installation of html-proofer
