sudo: false
language: ruby
rvm:
  - 2.1
script:
  - bundle exec jekyll build
  - bundle exec htmlproof ./_site --only-4xx --check-favicon --check-html
  - bundle exec httparty -f json "https://raw.githubusercontent.com/maptime/maptime.github.io/master/_data/chapters.json"
env:
  global:
    - NOKOGIRI_USE_SYSTEM_LIBRARIES=true # speeds up installation of html-proofer